# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: dunno_dev
  pool: 5
  username: dunno
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: dunno_test
  pool: 5
  username: dunno
  password:
  host: localhost

  production:
    adapter: "postgresql"
    pool: 5
    timeout: 5000
