# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3c300b8020153ece8c0b675475269285112f3678b2fdf365dd13abc63c5675ea4754182bd44f1198a4ae2219673bd69c3333080c87b38654b283e0d360df070

test:
  secret_key_base: b1dba0937335f90e6176a48fb624ccb658fe85846ebf606b3570c03dee48a1572ed9657c290471a3d1cbc0d0360ff95a0e53d5cf2d815d4199e0ba10646eba95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
